import { getPitchesForUser } from '@/lib/mockPitch';
import Link from "next/link";

import { auth } from '@clerk/nextjs/server';

export const dynamic = 'force-dynamic'; 

export default async function ShowcasePage() {
  const { userId } = await auth();

  const pitches = await getPitchesForUser(userId || 'guest');

  return (
    <div className="flex-1 p-6 md:p-10 h-full overflow-y-auto bg-bg-primary text-text-primary font-sans relative">
      <div className="max-w-6xl w-full mx-auto">
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-serif font-extrabold mb-4 tracking-tight">
            PitchSoup{" "}
            <span className="text-sienna-brown dark:text-blush-peach">
              Demo Day
            </span>
          </h1>
          <p className="text-xl text-text-secondary max-w-2xl font-sans">
            Discover the latest startup ideas generated by founders in the
            PitchSoup community.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {pitches?.map((pitch) => (
            <Link
              href={`/deck/${pitch.id}`}
              key={pitch.id}
              className="group bg-bg-floating border border-border-subtle rounded-2xl p-6 hover:border-sienna-brown/50 hover:shadow-subtle transition-all cursor-pointer flex flex-col relative overflow-hidden"
            >
              <div className="flex items-start justify-between mb-4 relative z-10">
                <h3 className="text-xl font-serif font-bold text-text-primary group-hover:text-sienna-brown dark:group-hover:text-blush-peach transition-colors line-clamp-1">
                  {pitch.startupName}
                </h3>
                <span className="bg-blush-peach/40 text-sienna-brown dark:text-blush-peach text-xs font-bold px-2 py-1 rounded">
                  Pitch Deck
                </span>
              </div>
              <p className="text-sm font-sans text-text-secondary flex-1 line-clamp-3 mb-6 relative z-10">
                {pitch.problem}
              </p>

              <div className="flex items-center justify-between pt-4 border-t border-border-subtle text-xs font-medium text-text-muted relative z-10">
                <div className="flex items-center gap-1.5 truncate pr-2">
                  <span className="material-symbols-outlined text-sm">
                    trending_up
                  </span>
                  <span className="truncate">Market: {pitch.targetMarket}</span>
                </div>
                <div className="flex items-center gap-1.5 whitespace-nowrap group-hover:text-sienna-brown dark:group-hover:text-blush-peach transition-colors text-text-secondary">
                  <span className="material-symbols-outlined text-sm">
                    visibility
                  </span>
                  View Deck
                </div>
              </div>

              {/* Subtle hover gradient inside card */}
              <div className="absolute inset-0 bg-sienna-brown/5 dark:bg-blush-peach/5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </Link>
          ))}

          {(!pitches || pitches.length === 0) && (
            <div className="col-span-full text-center py-20 text-text-muted">
              <span className="material-symbols-outlined text-4xl mb-2 opacity-50">
                inbox
              </span>
              <p>No pitches published yet. Be the first to generate a deck!</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
