import { supabase } from '@/lib/supabase';
import Link from "next/link";

export const revalidate = 0; 

export default async function ShowcasePage() {
  const { data: pitches } = await supabase.from("Pitch")
    .select("*")
    .order("createdAt", { ascending: false })
    .limit(20);

  return (
    <div className="flex-1 p-6 md:p-10 h-full overflow-y-auto bg-background text-foreground font-sans relative">
      <div className="max-w-6xl w-full mx-auto">
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-headline-xl font-extrabold mb-4 tracking-tight">
            PitchSoup{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">
              Demo Day
            </span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl font-body-lg">
            Discover the latest startup ideas generated by founders in the
            PitchSoup community.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {pitches?.map((pitch) => (
            <Link
              href={`/deck/${pitch.id}`}
              key={pitch.id}
              className="group glass-panel rounded-2xl p-6 hover:border-primary/50 hover:shadow-sm transition-all cursor-pointer flex flex-col relative overflow-hidden"
            >
              <div className="flex items-start justify-between mb-4 relative z-10">
                <h3 className="text-xl font-headline-sm font-bold group-hover:text-primary transition-colors line-clamp-1">
                  {pitch.startupName}
                </h3>
                <span className="bg-primary/10 text-primary text-xs font-bold px-2 py-1 rounded">
                  Pitch Deck
                </span>
              </div>
              <p className="text-sm font-body-md text-foreground/80 flex-1 line-clamp-3 mb-6 relative z-10">
                {pitch.problem}
              </p>

              <div className="flex items-center justify-between pt-4 border-t border-border/50 text-xs font-medium text-muted-foreground relative z-10">
                <div className="flex items-center gap-1.5 truncate pr-2">
                  <span className="material-symbols-outlined text-sm">
                    trending_up
                  </span>
                  <span className="truncate">Market: {pitch.targetMarket}</span>
                </div>
                <div className="flex items-center gap-1.5 whitespace-nowrap group-hover:text-primary transition-colors">
                  <span className="material-symbols-outlined text-sm">
                    visibility
                  </span>
                  View Deck
                </div>
              </div>

              {/* Subtle hover gradient inside card */}
              <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-secondary/5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </Link>
          ))}

          {(!pitches || pitches.length === 0) && (
            <div className="col-span-full text-center py-20 text-muted-foreground">
              <span className="material-symbols-outlined text-4xl mb-2 opacity-50">
                inbox
              </span>
              <p>No pitches published yet. Be the first to generate a deck!</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
